echo-sd: Do not exec zsh on module mode with bash 3-

diff --git a/echo-sd b/echo-sd
--- a/echo-sd
+++ b/echo-sd
@@ -94,20 +94,20 @@
 ##     http://dic.nicovideo.jp/a/%E7%AA%81%E7%84%B6%E3%81%AE%E6%AD%BB
 ##
 
-case "${BASH_VERSION-}" in
-[1-3].*)
-  if type zsh >/dev/null 2>&1; then
-    unset BASH_VERSION
-    exec zsh "$0" ${1+"$@"}
-    exit 1
-  fi
-  echo "${0##*/}: ERROR: bash 4 or later required" 1>&2
-  exit 1
-  ;;
-esac
-
 if [[ ${0##*/} == echo-sd ]] && [[ ${zsh_eval_context-toplevel} == toplevel ]]; then
   set -u
+
+  case "${BASH_VERSION-}" in
+  [1-3].*)
+    if type zsh >/dev/null 2>&1; then
+      unset BASH_VERSION
+      exec zsh "$0" ${1+"$@"}
+      exit 1
+    fi
+    echo "${0##*/}: ERROR: bash 4 or later required" 1>&2
+    exit 1
+    ;;
+  esac
 fi
 
 typeset SD_arg0="$0"
